export const accountRows = [
  {
    name: 'Northstar Logistics',
    owner: 'Camila Souza',
    segment: 'Enterprise',
    health: 'Strong',
    mrr: '$28,400',
    renewal: 'May 18',
  },
  {
    name: 'Apex Health Group',
    owner: 'Rafael Lima',
    segment: 'Mid-market',
    health: 'Watch',
    mrr: '$16,900',
    renewal: 'May 23',
  },
  {
    name: 'BluePeak Retail',
    owner: 'Isabela Costa',
    segment: 'Growth',
    health: 'Strong',
    mrr: '$9,300',
    renewal: 'Jun 02',
  },
  {
    name: 'Vertex Capital',
    owner: 'Marcos Reis',
    segment: 'Enterprise',
    health: 'Risk',
    mrr: '$22,150',
    renewal: 'Jun 10',
  },
  {
    name: 'Nimbus Foods',
    owner: 'Larissa Prado',
    segment: 'Growth',
    health: 'Strong',
    mrr: '$8,240',
    renewal: 'Jun 12',
  },
  {
    name: 'Atlas Mobility',
    owner: 'Eduardo Nunes',
    segment: 'Enterprise',
    health: 'Watch',
    mrr: '$31,800',
    renewal: 'Jun 17',
  },
  {
    name: 'Cora Education',
    owner: 'Priscila Moraes',
    segment: 'Mid-market',
    health: 'Strong',
    mrr: '$14,560',
    renewal: 'Jun 19',
  },
  {
    name: 'Velo Clinic',
    owner: 'Thiago Barreto',
    segment: 'Growth',
    health: 'Risk',
    mrr: '$7,980',
    renewal: 'Jun 25',
  },
  {
    name: 'Signal Energy',
    owner: 'Juliana Duarte',
    segment: 'Enterprise',
    health: 'Strong',
    mrr: '$26,700',
    renewal: 'Jul 01',
  },
  {
    name: 'Orbit Commerce',
    owner: 'Felipe Assis',
    segment: 'Mid-market',
    health: 'Watch',
    mrr: '$13,420',
    renewal: 'Jul 03',
  },
  {
    name: 'Harbor Security',
    owner: 'Bianca Teixeira',
    segment: 'Enterprise',
    health: 'Strong',
    mrr: '$19,850',
    renewal: 'Jul 08',
  },
  {
    name: 'Lumen Studio',
    owner: 'Caio Ventura',
    segment: 'Growth',
    health: 'Strong',
    mrr: '$6,750',
    renewal: 'Jul 10',
  },
]
